message = 'corona vaccine is ready to use, most of them are more than 90% effective!'
print(message)
print(message.capitalize())
Message = message.capitalize()
print(Message)

print(dir(message))
print(message.upper())
print(message.islower())
print(message.isupper())
print(message.isalnum())
print(message.find('ready'))
print(message[18:24])
print(message.find('not'))
print('############')
seq1 = ('192', '168', '48', '90')
print('.'.join(seq1))
print("-".join(seq1))
print('/'.join(seq1))
print(seq1)
print('############')
mountains = ['Everest', 'Himalaya', 'Sahyadri', 'Alps', 'K2', 'Mt Hood']
print(mountains)
mountains.append('Oregon mount')
print(mountains)
mountains.extend(['Mt rainer', 'Satpuda'])
print(mountains)
mountains.insert(2, 'Mt Abu')
print(mountains)
mountains.pop()
print(mountains)
print(mountains.pop())
print(mountains)
mountains.pop(5)
print(mountains)
print('##########################################')
cntr_empl = {'Name': 'Santa', 'Skill': 'BlockChain', 'Code': 1024}
print(cntr_empl)
print(cntr_empl.keys())
print(cntr_empl.values())
cntr_empl.clear()
print(cntr_empl)
